create-venv:
	python -m venv venv
activate:
	source ./venv/bin/activate
install-django:
	pip install django==3.2
startproject:
	django-admin startproject projectname
startapp:
	django-admin startapp products
start:
	python manage.py runserver
