create-venv:
	python -m venv venv
activate-venv:
	source ./venv/bin/activate
install-django:
	pip install django==3.2
startproject:
	django-admin startproject projectname
startapp:
	django-admin startapp products
start-server:
	python manage.py runserver
python-console:
	python manage.py shell
