# Generated by Django 3.2 on 2023-06-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_name',
            new_name='category_name',
        ),
    ]
